Bug fixes and additional tests.
InputFramer: Fixed a bug where continuation frames weren't handled properly.

HTTPMessage: Fixed a runtime error caused by assuming Data objects always
start at index 0 and end at count-1.

Testing: Added QuirkyTestServer to allow HTTP responses and WebSocket
frames to be generated with various errors. Also added several more tests.

WebSocket: Cleaned up connection logic a bit, fixed a faulty precondition, and made some
enums Equatable.

WebSocketError: Added conformance to CustomDebugStringConvertible.